server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/juanpapiro/ead-config-server-repo'
          default-label: main
          username: juanpapiro
          password: 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

ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
    
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
